env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - prettier
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoid-escape
  semi:
    - error
    - always

  prettier/prettier:
    [
      "error",
      {
        linebreakStyle: "unix",
        trailingComma: "es5",
        tabWidth: 2,
        semi: true,
        singleQuote: true,
        useTabs: true,
      },
    ]
